// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgWsOMziqqWW_85jwGfInFcjLPO0XOwe8',
    appId: '1:226226285142:web:3dff1a53910bf21ddee9f7',
    messagingSenderId: '226226285142',
    projectId: 'music-services-firebase',
    authDomain: 'music-services-firebase.firebaseapp.com',
    storageBucket: 'music-services-firebase.firebasestorage.app',
    measurementId: 'G-ZDVZ6W5JWX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWeJeRe9O3HVEsw2zy0Dt3yYhKJ5ukOLk',
    appId: '1:226226285142:ios:48c25e46946a4997dee9f7',
    messagingSenderId: '226226285142',
    projectId: 'music-services-firebase',
    storageBucket: 'music-services-firebase.firebasestorage.app',
    iosBundleId: 'com.example.musicServicesModuleAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWeJeRe9O3HVEsw2zy0Dt3yYhKJ5ukOLk',
    appId: '1:226226285142:ios:48c25e46946a4997dee9f7',
    messagingSenderId: '226226285142',
    projectId: 'music-services-firebase',
    storageBucket: 'music-services-firebase.firebasestorage.app',
    iosBundleId: 'com.example.musicServicesModuleAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgWsOMziqqWW_85jwGfInFcjLPO0XOwe8',
    appId: '1:226226285142:web:473cb49b738129cfdee9f7',
    messagingSenderId: '226226285142',
    projectId: 'music-services-firebase',
    authDomain: 'music-services-firebase.firebaseapp.com',
    storageBucket: 'music-services-firebase.firebasestorage.app',
    measurementId: 'G-TJ071F5TX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVlGsT1yxBoVUWt5L4AfYvK0l7SXefhwk',
    appId: '1:226226285142:android:f13a9d5435966760dee9f7',
    messagingSenderId: '226226285142',
    projectId: 'music-services-firebase',
    storageBucket: 'music-services-firebase.firebasestorage.app',
  );

}